### PR TITLE
Github CI

### PR DESCRIPTION
**Pull request by hannesa2**
It's based on #92 to let CI run

### CODE REVIEW

**Comment by hannesa2** [comment]
I guess, you have to enable Github actions 
image

Here you have a running example https://github.com/hannesa2/The-Endergetic-Expansion/pull/1/checks?check_run_id=1140320661

**Review by SmellyModder — APPROVED** [review]
Local and third-party actions are enabled for this repository.
I could see this PR being somewhat useful.

**Comment by hannesa2** [comment]
> Here you have a running example https://github.com/hannesa2/The-Endergetic-Expansion/pull/1/checks?check_run_id=1140320661

Sorry on your repo it doesn't start, I linked a running example, when repo  has the right settings

**Comment by SmellyModder** [comment]
Local and third-party actions are enabled for this repository, there must be something else wrong then.

**Comment by hannesa2** [comment]
Who can merge it ?

**Pull request merged**
