### PR TITLE
Add cullface to acidian lanterns

### PR DESCRIPTION
**Pull request by muzikbike**
Would have done the same for puffbug hives but their model doesn't seem to be available at all

### CODE REVIEW

**Comment by SmellyModder** [comment]
What is the point of this exactly?

**Comment by SmellyModder** [comment]
Can you show what new advantage this brings?

**Comment by muzikbike** [comment]
Pretty much standard for vanilla models to implement cullface for faces which can be fully obscured by other blocks, as well as outright delete faces which can never be seen in normal gameplay, as the game doesn't need to render said faces.

**Comment by SmellyModder** [comment]
I would like a screenshot showing that it works

**Comment by muzikbike** [comment]
Before:




After:

**Comment by SmellyModder** [comment]
I need to ensure it works on all its facing directions, please send screenshots for every direction of the lantern.

**Comment by SmellyModder** [comment]
image
Uhhh, why does it have no face when no block is blocking its faces there?

**Comment by muzikbike** [comment]
Because that's looking from below

**Comment by muzikbike** [comment]
To clarify:

**Pull request merged**
