### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by bucketBrian**
Co-authored-by: ChuijkYahus <94828194+ChuijkYahus@users.noreply.github.com>

### CODE REVIEW

**Comment by SmellyModder** [comment]
I think I'm going to wait a bit for @Kasualix to maybe take a look at this.
They did the initial translations.

**Comment by Kasualix** [comment]
> I think I'm going to wait a bit for @Kasualix to maybe take a look at this. They did the initial translations.

The initial zh_cn.json is made by @1mtwtfss1 and I was just a helper sending the PR as he had difficulty accessing GitHub.

This PR's authors are mainly active and experienced contributors from [CFPA](https://github.com/CFPAOrg) (known translation team in China) so you can trust them :)

**Comment by bucketBrian** [comment]
> > I think I'm going to wait a bit for @Kasualix to maybe take a look at this. They did the initial translations.
> 
> The initial zh_cn.json is made by @1mtwtfss1 and I was just a helper sending the PR as he had difficulty accessing GitHub.
> 
> This PR's authors are mainly active and experienced contributors from [CFPA](https://github.com/CFPAOrg) (known translation team in China) so you can trust them :)

@Kasualix

Just for clarify, what specifically the "This PR's authors" referring to? @1mtwtfss1 or @ChuijkYahus and me?
I just afraid of if abnormals just keep waiting that guy(1mtwtfss1) and everything just get stuck over here.😂

**Comment by Kasualix** [comment]
"This PR's authors" refers to you and Chuijk.

**Review by SmellyModder — APPROVED** [review]

**Pull request merged**
