### PR TITLE
Make gradle executeable on Mac/Linux out of the box

### PR DESCRIPTION
**Pull request by hannesa2**
otherwise you run into this

image

### CODE REVIEW

**Comment by SmellyModder** [comment]
GitHub is showing no changes for the `gradlew` file?

**Comment by SmellyModder** [comment]
And doesn't #92 take care of this?

**Comment by hannesa2** [comment]
> GitHub is showing no changes for the `gradlew` file?

It does, look
image

**Comment by hannesa2** [comment]
> And doesn't #92 take care of this?

**Comment by hannesa2** [comment]
Sorry, I accidentally close (and reopen) this pull request

**Comment by SmellyModder** [comment]
Both PRs' diffs for the `gradlew` file say `0 additions and 0 deletions`, so I'm unsure why they're included in these PRs?

**Comment by hannesa2** [comment]
Again, the access right is changed (in Linux with `chmod`)

https://en.wikipedia.org/wiki/Chmod

image

**Pull request merged**
